### ISSUE TITLE
irb2400 ikfast plugin fails to build after groovy update

### ISSUE THREAD

**Issue by jrgnicho** [ros-industrial/abb#1]
update in groovy changed the function signatures of the kinematics_base.h file. As a result, the irb_2400_manipulator_ikfast_moveit_plugin.cpp fails to build since it can't find any implementation of the base class' virtual methods.  Will create a branch for this issue

**Comment by shaun-edwards** [comment]
Jeremy is aware of this bug as well.  You might want to talk to him about it.

**Comment by JeremyZoss** [comment]
See changes they made to the moveit ikfast templates that probably address this same API change (8230ace255bfcc23665ddf6aa894e76858870b9e, e0d1b58e05da5a39e4a428ed654c81d83651864e).  That plugin seems to totally ignore the parameter, though.

I think the right response is to update the API to match the new signatures and then replace any references to "lock_redundant_joints" with "options.lock_redundant_joints".  We may also consider checking for "options.return_approximate_solution" and logging a WARN_ONCE if called with that unsupported option.

Long-term, the better answer is to probably re-generate the ABB plugin from the "official" [moveit_ikfast](https://github.com/ros-planning/moveit_ikfast) template generator, to keep things consistent when changes are made in the future.

**Comment by shaun-edwards** [comment]
Does this bug affect the released version of ABB (i.e. the google code version that the debs are built from)?  If so can you please back port the fix to the google code groovy branch as well?
