### ISSUE TITLE
'Installing the ABB ROS Server' tutorial refers to non-existing 'abb_common'

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/abb#102]
Under section `3 Installing Server Code` ([here](http://wiki.ros.org/abb/Tutorials/InstallServer)):

> All files in the [abb_common/rapid](http://wiki.ros.org/abb/Tutorials/InstallServer#Installing_Server_Code) directory should be copied to the robot controller [..]

The `abb_common` package was deprecated in Hydro, and removed in Indigo. The instructions work because they explicitly link to the old Groovy files.

The text and link should be updated. The tutorial should probably be updated to give different instructions for the different releases.

**Comment by gavanderhoorn** [comment]
Fixed in [abb/Tutorials/InstallServer?action=diff&rev2=13&rev1=12](http://wiki.ros.org/action/info/abb/Tutorials/InstallServer?action=diff&rev2=13&rev1=12).

Left `abb_common` in for Hydro and older distributions, and pointed to `abb_driver` for Indigo and newer.

**Comment by gavanderhoorn** [comment]
Also updated the RobotStudio tutorial ([abb/Tutorials/RobotStudio?action=diff&rev2=7&rev1=6](http://wiki.ros.org/action/info/abb/Tutorials/RobotStudio?action=diff&rev2=7&rev1=6)).

**Comment by Levi-Armstrong** [comment]
Thank you!
