### ISSUE TITLE
controller is taking too long to execute trajectory

### ISSUE THREAD

**Issue by xsmxsm** [ros-industrial/abb#110]
![img_20161109_085428](https://cloud.githubusercontent.com/assets/16012809/20124328/96f88a9c-a660-11e6-80b0-26527020b05d.jpg)

**Comment by shaun-edwards** [comment]
http://answers.ros.org/question/196586/how-do-i-disable-execution_duration_monitoring/

**Comment by gavanderhoorn** [comment]
@xsmxsm: the link @shaun-edwards posted should help you get this resolved.

In addition: could I ask you to please not use screenshots for things that are essentially text? Please copy-paste the console window text in the future. Text in images is (currently) not searchable, which reduces visibility of this issue report.

Thanks.
