### ISSUE TITLE
Error in T_ROB1 - ROS_socket -Line 31

### ISSUE THREAD

**Issue by ghost** [ros-industrial/abb#147]
Hi, I have followed the ROS tutorials, but while doing PP to Main option, I'm getting the error "T_ROB1 - ROS_socket -Line 31" Description- Reference to Unknown function SocketGetStatus.

I'm using ABB IRB 1200 Manipulator with ROS kinetic and Robot Studio Version 6.0.

**Comment by gavanderhoorn** [comment]
Please make sure you have option `672-1` *Socket Messaging* or `616-1` *PC Interface* on your robot.

If not, the driver won't work.

Check [ros/wiki/abb_driver](http://wiki.ros.org/abb_driver), section *Requirements*, and the [Installing the ABB ROS Server](http://wiki.ros.org/abb/Tutorials/InstallServer) tutorial, section *Prerequisites*.

**Comment by gavanderhoorn** [comment]
I'm closing this, as it's most likely a misconfiguration or missing option and not an issue with the packages in this repository. You can continue commenting though.
