### ISSUE TITLE
Problem working with real IRB 1200 robot

### ISSUE THREAD

**Issue by rajmohan747** [ros-industrial/abb#156]
Hi,
I am with IRB 1200 in ROS-Kinetic platform.
Initially I am launching 

```
roslaunch abb_irb1200_support robot_interface_streaming_irb1200_5_90.launch robot_ip:=192.168.125
```

Since I'm working with real robot, _sim_ parameter was set as `True`. On launching ,

```
roslaunch abb_irb1200_5_90_moveit_config moveit_planning_execution.launch sim:=false robot_ip:=192.168.125.1
```

I am facing an error as `robot_interface_streaming_irb1200_5_90.launch` is not available.

Also tried replacing `robot_interface_streaming_irb1200_5_90.launch` with `robot_interface_download_irb1200_5_90.launch`.

After that on launching the node to move the robot,the teach pendant is showing like:

```
Sending  24 points to MOTION Task.  Traj START received Traj END received
```

But the robot is still not moving

Please correct me, if I'm doing something wrong

**Comment by gavanderhoorn** [comment]
For both of you: did you follow the [installation and setup tutorials](http://wiki.ros.org/abb/Tutorials)?

**Comment by rajmohan747** [comment]
@gavanderhoorn : Yes ,I followed the same procedure only.

**Comment by gavanderhoorn** [comment]
Please see whether #155 fixes this.

**Comment by gavanderhoorn** [comment]
I'm going to close this as I believe #155 fixes what @rajmohan747 described.

If that is not the case then please re-open and clarify.
