### ISSUE TITLE
Support package GoFa CRB 15000

### ISSUE THREAD

**Issue by DavidJenny** [ros-industrial/abb#186]
Is there already a plan in the pipeline to release a support package for CRB15000? A urdf would be quite helpful to start with.

**Comment by gavanderhoorn** [comment]
What about https://github.com/ros-industrial/abb_experimental/pull/127?

**Comment by DavidJenny** [comment]
Thanks a lot, wasn't aware of this!

**Comment by gavanderhoorn** [comment]
If you could test it and verify it's correct, that would help getting it merged.

**Comment by DavidJenny** [comment]
My plan is to work in simulation for now to see if it fits our application but I have a chance to test with the hardware this summer. Will keep you updated!

**Comment by gavanderhoorn** [comment]
Checking it against RobotStudio and/or the specifications would already be valuable.

**Comment by gavanderhoorn** [comment]
@DavidJenny: have you had a chance to test the package?
