### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by bchretien** [ros-industrial/abb#27]
Hi!

I am in charge of Hydro packaging for Arch Linux, and several users told me they were interested in `abb`. However, none of the packages have been released apparently. Is there any particular reason for that? If not, would it be possible to release the packages with `bloom`?

Thanks!

**Comment by shaun-edwards** [comment]
@bchretien, I am currently working on the release.  It should come out in a couple of weeks.  I'm just working on some final fixes/mods before the release.

**Comment by bchretien** [comment]
cc @Samsagax

@shaun-edwards ok, thanks for the information!

**Comment by Samsagax** [comment]
Thanks @bchretien for cc-ing me. I'm compiling from source and just made a connection to an irb-1600 in hydro. I'll try to make an urdf for my robot as well.

Hope this is released soon so I can add it to my distribution.

**Comment by Levi-Armstrong** [comment]
@shaun-edwards, should this issue be closed due to the release of 1.1.4?
