### ISSUE TITLE
Manipulator variants naming convention

### ISSUE THREAD

**Issue by Samsagax** [ros-industrial/abb#29]
This is a bit silly. But what naming convention should we use for packages of different robot variants (i.e. IRB-1600-1.2, IRB-1600-1.65 and so on)?

According to the [ROS naming convention](http://wiki.ros.org/ROS/Patterns/Conventions#Packages), dots are not allowed, so my question goes for the dot in those variants specifications.

Should we use an underscore like `IRB-1600-1.2 -> irb_1600_1_2`?

Or should we ommit the dot entirely `IRB-1600-1.2 -> irb_1600_12`?

I would go for the first one.

**Comment by gavanderhoorn** [comment]
Not really well known (as it's only referenced from the tutorials pages), but we have some guidelines for naming artefacts in ROS-Industrial. See [here](http://wiki.ros.org/Industrial/Tutorials/SuggestedPackageLayoutNewRepositories) for the ROS wiki page, and [here](https://github.com/gavanderhoorn/rep/blob/repository_layout/rep-xxxx.rst) for a draft version of a possible REP.

The [fanuc](https://github.com/ros-industrial/fanuc) and [fanuc_experimental](https://github.com/ros-industrial/fanuc_experimental) repositories can both serve as examples of what the above referenced documents describe.

---

So for your question specifically: you could create a `abb_irb1600_support` package, which would contain all variants of the 'base' IRB-1600 model. The main `abb` repository currently doesn't follow that model yet, but it will be converted to the new layout. The [abb_experimental](https://github.com/ros-industrial/abb_experimental) repository contains a `abb_irb4400_support` package which can serve as an example.

This would remove the '1.2' from the package name at least (but move it to the naming of the urdf/xacros and entities within those files). I think it would be a good thing to wait for some more opinions here, as the dot-case isn't covered by the current guidelines.

**Comment by shaun-edwards** [comment]
The `"_"` generally replaces the `" "`, so lets stick with that convention.  Since the `.` is not allowed to be in package names, we should probably not use it in file names or urdf xacros.  I'd like to stay consistent across all of these in order to avoid confusion (all the names should match).  So I guess this means we just leave the `.` out of the name.

**Comment by Samsagax** [comment]
We should add all 1600 variants in a support package then, with subdirectories for each variant.
