### ISSUE TITLE
URDF tool0 frames do not match the ABB tool0 orientation.

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/abb#32]
There is/was some ambiguity in the ROS-Industrial documentation about the tool0 frame (see [here](http://wiki.ros.org/Industrial/Tutorials/Create%20a%20URDF%20for%20an%20Industrial%20Robot)).  The original intent of tool0 was to match exactly (pose & orientation) of the robot tool0.  This would allow a comparison between ROS-I reported positions and controller positions for tool0.  However, due to conflicting requirements for creating URDF (i.e. a preferred orientation of frames), the tool0 has not always matched the robot controller frame.
Reference: #31

**Comment by Samsagax** [comment]
To keep both compatibilities I suggest to add two tools: one according to the ROS-I documentation (generic `tool0`) and other according to each robot manufacturer's choice of reference (and naming it something like `ABB_tool0`) So depending on each manufacturer we can use the manufacturer-provided tool0 and one tool0 according to ROS-I conventions.

**Comment by gavanderhoorn** [comment]
@Samsagax: I'm wondering which ROS conventions you are refering to? ROS specifies a right-handed coordinate system, with Z up, X to 'the front' and Y to 'the left'. That doesn't mean we can't rotate it in place, AFAIU.

For backward compatibility, we can just leave the toolframes as they are in the existing urdfs, but make sure that all new support packages (such as your IRB-1600) _do_ have the correct toolframe. We can then deprecate the `abb_common` package (or at least the urdf bits in it), and gradually phase it out over 2 ROS distributions (ie: deprecate in Hydro, remove in Indigo).

Also, I'm not really sure I like the idea of adding 2 tool links, as this would negate the advantage of having the `tool0` link in the first place (having a standardised EEF attachment point on all robot urdfs). As @shaun-edwards wrote: the intent of the ROS-I tutorial was to "_have the `tool0` link match exactly the robot tool frame_" (ie: the complete pose, not just the position). Adding multiple tool links would also become confusing I think, as a Fanuc (fi) can have up to 10 different tool frames.

**Comment by Samsagax** [comment]
> @Samsagax: I'm wondering which ROS conventions you are refering to? ROS specifies a right-handed coordinate system, with Z up, X to 'the front' and Y to 'the left'. That doesn't mean we can't rotate it in place, AFAIU.

@gavanderhoorn: I reffer to exactly that, the convention adopted by ROS-I is "X-axis pointing to the front in the 'zero' position", and ABB (don't know exactly about others) use the Z-axis pointing to the front (that's tool0's default position).

And I agree it can be a mess about having two or more tool0's but the problem is that references in the ROS-I world and the IRC-5 controller won't match. That's specially dangerous and error prone if we want to do something like pose-based trajectory downloading (i.e. using the IRC-5's MoveL/J interpolation)
