### ISSUE TITLE
Support for RobotStatus.msg

### ISSUE THREAD

**Issue by Samsagax** [ros-industrial/abb#34]
I was looking for a way to teleoperate the irb-1600 in our lab and I looked into writing some servers to get the robot status. It's fairly simple to add RobotStatus msg to the existing server, provided some EIO.cfg tweaking inside the IRC-5.

On the stateServer (IRC-5) side we need to add:
- A virtual I/O unit to declare some status Digital Outputs and connect them to the corresponding System Output (ref: IRC-5 System Parameters Manual, Topic I/O, Type System Output):
  - `/RobotMode mode` reporting: Use `Auto On` (Auto mode when 1, Manual or Manual 100% when 0)
  - `/TriState e_stopped` reporting: Use `Emergency Stop` (1 when EStop, 0 Otherwhise) possibly in combination with `Run Chain OK`
  - `/TriState drives_powered` reporting: Use `Motors ON State` (1 when Drivers are enabled, 0 otherwise), take note that breakes are not released until the manipulator moves for the first time.
  - `/TriState motion_possible` reporting: This is a bit tricky, we need a combination of `Motors ON State`, `Task Executing` (with `Argument2` set to the motion task executing ROS movements) and `Cycle On`.
  - `/TriState in_motion` reporting: use `Mechanical Unit Not Moving` (0 when moving, 1 otherwise), according to documentation this signal is down if the task is executing but the manipulator is steady (i.e. TCP Speed is 0).
  - `/TriState in_error`: use `Execution Error` for just errors in the program.

In the client side is all already there as the abb_robot_state_node runs a RobotStateInterface.

**Comment by shaun-edwards** [comment]
@Samsagax, this seems like a good plan.  Are you willing to implement it?

**Comment by Samsagax** [comment]
Sure. The only question I have is if I Have to add a new message with different signature to the existing server? Or append the data to the current message?

Joaquín Ignacio Aramendía

**Comment by shaun-edwards** [comment]
That definitely wasn't easy to track down (I should add it to the wiki).  The message should be sent on the same connection as the joint states, but with a different ID, 13 (see [here](http://docs.ros.org/hydro/api/simple_message/html/simple__message_8h_source.html#l00058)).

The header info should be similar to joint states (except with the different ID).  The data payload should is described [here](https://github.com/ros-industrial/industrial_core/blob/hydro-devel/simple_message/include/simple_message/robot_status.h#L95)

**Comment by Samsagax** [comment]
I added an empty message for now, the problem is for reporting all that stuff, we need to instruct the user to configure some system parameters, I have the text for the wiki, but how I mark it as "experimental" or "in-development" feature?

**Comment by gavanderhoorn** [comment]
You could possibly use an [admonition](http://moinmo.in/HelpOnAdmonitions). I've used a few in the [fanuc tutorials](http://wiki.ros.org/fanuc/Tutorials). If you don't want to include the icon bit, you could just use a coloured 'box' (like on the [indigo](http://wiki.ros.org/indigo) landing page on the ROS wiki).

**Comment by gavanderhoorn** [comment]
Is documentation the main blocker here? I think the rapid code looks sane enough. I would just set all fields initially to _tristate unknown_ (-1) instead of zeros.

**Comment by Samsagax** [comment]
Guys. Sorry to be out of the radar for a while. I've switched jobs and I no longer have a real robot to test things on. Maybe I could write some code and someone can test it for me, or maybe I can convince my new boss to engage in development of new things involving ROS ;)

Hope I can be on track soon.

**Comment by gavanderhoorn** [comment]
Welcome back :). ABB Robot Studio is free to use, afaik, right?

**Comment by shaun-edwards** [comment]
I don't think it is, but if @Samsagax is serious, we can see what we can do.

**Comment by gavanderhoorn** [comment]
On 12-1-2015 5:41, Shaun Edwards wrote:

> I don't think it is, but if @Samsagax is serious, we can see what we can do.

Oh, right. It is a 30-day trial.

**Comment by Samsagax** [comment]
Yes, it is a 30-day trial. And maybe i can use a virtual machine to test. The "hard" part is editing the robot configuration to get he info we need

**Comment by gavanderhoorn** [comment]
I've recently worked with an ABB robot and the lack of `STATUS` support was quite annoying. Even if (as @Samsagax writes) setting up the controller properly for this would be difficult, it would still be nice if we at least give users the option to do it.

Could we perhaps as a first iteration just send _tristate unknown_s (-1) for all fields? Than at least part of the infrastructure on the server side would be there.

**Comment by gavanderhoorn** [comment]
This will be added by #145.

See [wiki/abb/Tutorials/InstallServer - diff](http://wiki.ros.org/action/info/abb/Tutorials/InstallServer?action=diff&rev2=18&rev1=14) for the documentation that was added.

**Comment by gavanderhoorn** [comment]
With the merge of #168 (rebased version of #145) this is now supported by the driver.
