### ISSUE TITLE
Regnerate irb2400 plugin

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/abb#38]
The irb2400 plugin was generated some time ago.  It should be regenerated to take advantage of new changes and updates.

See #36

**Comment by JeremyZoss** [comment]
Updating to the current `moveit_ikfast` plugin template should also remove the compiler warnings about deprecated `tf::PoseMsgToKDL` calls (it's been renamed to `tf::poseMsgToKDL`).

**Comment by gavanderhoorn** [comment]
This can probably be closed. #43 included a newly generated plugin, which doesn't have the issues described by @JeremyZoss.
