### ISSUE TITLE
Add variant support

### ISSUE THREAD

**Issue by JeremyZoss** [ros-industrial/abb#47]
Several of the currently-listed models (2400, 6640, etc.) actually have multiple variants with different arm lengths, payloads, etc.  We should update the packages to be more specific about which variant is actually modeled.  This will involve renaming of all current affected packages to be variant-specific, so we'll probably need to mark the current versions as deprecated first, to give users time to adapt.
- [IRB 2400](http://new.abb.com/products/robotics/industrial-robots/irb-2400/irb-2400-data) : 2 variants, which appear to only differ in payload capacity but may have different CAD models
- [IRB 6640](http://new.abb.com/products/robotics/industrial-robots/irb-6640/irb-6640-data) : 7 variants that differ in arm length, payload, joint range, etc.

**Comment by gavanderhoorn** [comment]
There's some more work to do, but with the recent merge of #123, #122 and #121 I think we're on our way.

Do you think we can close this issue @JeremyZoss ?

**Comment by JeremyZoss** [comment]
Agreed.
