### ISSUE TITLE
Cherry-pick issue #42 fix to hydro and then release

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/abb#70]
Issue #42 is a true bug.  It should be back ported to the hydro release.

**Comment by shaun-edwards** [comment]
@Levi-Armstrong, I can help you through this.  It will be good for you to learn how to do a release.

**Comment by Levi-Armstrong** [comment]
@shaun-edwards, I recently noticed that there is a rapid folder in the abb_common which was not addressed by the #42 fix; would like me to submit a pull request to fix this prior to fixing this issue?

**Comment by shaun-edwards** [comment]
Let's go ahead an fix it in `abb_common`.  We can then cherry-pick those two fixes into the `hydro` branch.

**Comment by Levi-Armstrong** [comment]
@shaun-edwards, I have submitted PR #73 to fix the driver in abb_common, please review.

**Comment by Levi-Armstrong** [comment]
Addressed by PR #74
