### ISSUE TITLE
Bump minor nr for Indigo release

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/abb#78]
Suggestion: please bump the minor nr for the Indigo release (so make it `1.2.x`), similar to what was done with `industrial_core` (`0.3.x` -> `0.4.x`).

That would leave room to release additional versions into Hydro, and also make it clear which release a particular version of `abb` is meant for (ie: `1.1.x` -> Hydro, `1.2.x` -> Indigo).

**Comment by shaun-edwards** [comment]
This is my fault...I gave @Levi-Armstrong, the wrong direction.  We should follow [semantic versioning](http://semver.org/).

**Comment by Levi-Armstrong** [comment]
This issue is addressed by this [pull request](https://github.com/ros/rosdistro/pull/8624).

**Comment by gavanderhoorn** [comment]
Can probably close this now?
