### ISSUE TITLE
How to control abb walked along the circular path？

### ISSUE THREAD

**Issue by james2254** [ros-industrial/abb#93]
@shaun-edwards I have download the abb packages and i also can run the nodes 。But i can‘t control the abb totally。For example ，how can i control the abb to walk along with the circular path？

BEST WISH!

**Comment by shaun-edwards** [comment]
The interface for the abb robot only allows joint motion.  In order to perform cartesian motion, you will need to use a planning framework like MoveIt or Descartes.  What are you trying to do?

**Comment by james2254** [comment]
I will use Moveit
