### ISSUE TITLE
Support for ABB IRB 120? 

### ISSUE THREAD

**Issue by SteveMacenski** [ros-industrial/abb#96]
Hi!

I'm starting to do work with an ABB IRB 120 and wondering if there was support for this via moveit_configs or URDF/XACRO files to jump off from. 

Thanks!

**Comment by gavanderhoorn** [comment]
Please see the packages in [abb_experimental](https://github.com/ros-industrial/abb_experimental).

**Comment by SteveMacenski** [comment]
Awesome, thanks! I hadn't seen that before. I appreciate the help!

**Comment by SteveMacenski** [comment]
For the ABB_experimental, should I grab the abb_driver node from this repo as the abb_experimental software does not include robot hardware drivers?

**Comment by gavanderhoorn** [comment]
On 9-2-2016 5:37, Steven Macenski wrote:

> For the ABB_experimental, should I grab the abb_driver node from this repo as the abb_experimental software does not include robot hardware drivers?

Yes. Experimental repositories provide /additional/ packages, that are waiting to be migrated to the non-experimental repositories. For everything else you should just use either released or non-experimental packages.

Also: a `rosdep check --from-paths /path/to/your/catkin_ws/src --ignore-src` would've suggested this as well.

**Comment by SteveMacenski** [comment]
Thanks! Is there some documentation or discussion as to how to use this ROS system with the hardware? (computer to controller/robot interface, sp. launch files for hardware, etc) If one doesn't exist, I would like to assist in making one. I think that would greatly help the new ABB and ROS users.

**Comment by gavanderhoorn** [comment]
See [wiki.ros.org/abb](http://wiki.ros.org/abb). And then the various _tutorials_.

**Comment by gavanderhoorn** [comment]
re: 'launch files for hardware', see [WorkingWithRosIndustrialRobotSupportPackages](http://wiki.ros.org/Industrial/Tutorials/WorkingWithRosIndustrialRobotSupportPackages).

For general ROS questions: [answers.ros.org](http://answers.ros.org/questions/).

We always welcome (constructive) criticism, so if you feel something isn't correct, or missing, let us know.

**Comment by SteveMacenski** [comment]
Thanks for the links! My confusion is mostly when reading the tutorials from the wiki.ros.org/abb/Tutorials. Am I correct in saying those are the steps required on the controller to configure it for taking ROS commands? I'm not sitting in front of the controller right now, but then is there a USB port or something I'm supposed to plug-in to with a computer running ROS that is generating the commands? Or doe the controller include some computer I should load ROS onto and operate from that? 
Thanks

**Comment by gavanderhoorn** [comment]
The documentation expects some familiarity with setting up and configuring ABB controllers, and a basic understanding of ROS. I would highly recommend reading up on both before trying any of this.

As to your questions: the tutorials shows how to install the necessary files on the controller and how to configure it. Communication between the controller and your ROS pc (which is _not_ inside your controller) is done over standard TCP/IP.

Note that running the driver in RobotStudio is also supported, so you could start with that.

**Comment by SteveMacenski** [comment]
I have a good amount of experience with ROS, but the ABB controllers is something new to me. From looking inside of it, there isn't a clear 'plug in auxiliary computer here', referencing user guide as soon as I can get my hands on a copy.
